// AUTO-GENERATED by scripts/process-service-images.mjs — do not edit
export type ServiceImages = { card: string; gallery: string[] };
export const SERVICE_IMAGES: Record<string, ServiceImages> = {
  "flower-beds": {
    "card": "/images/services/flower-beds/favorite-card.webp",
    "gallery": [
      "/images/services/flower-beds/favorite-gallery.webp",
      "/images/services/flower-beds/img-0267-gallery.webp",
      "/images/services/flower-beds/img-0268-gallery.webp",
      "/images/services/flower-beds/img-0269-gallery.webp",
      "/images/services/flower-beds/img-0270-gallery.webp",
      "/images/services/flower-beds/img-1551-gallery.webp",
      "/images/services/flower-beds/img-1553-gallery.webp",
      "/images/services/flower-beds/img-1557-gallery.webp",
      "/images/services/flower-beds/img-1558-gallery.webp",
      "/images/services/flower-beds/img-1685-gallery.webp",
      "/images/services/flower-beds/img-1687-gallery.webp",
      "/images/services/flower-beds/img-1688-gallery.webp",
      "/images/services/flower-beds/img-1743-gallery.webp",
      "/images/services/flower-beds/img-5478-gallery.webp",
      "/images/services/flower-beds/img-5479-gallery.webp",
      "/images/services/flower-beds/img-5503-gallery.webp"
    ]
  },
  "french-drains": {
    "card": "/images/services/french-drains/favorite-card.webp",
    "gallery": [
      "/images/services/french-drains/favorite-gallery.webp",
      "/images/services/french-drains/img-1484-gallery.webp",
      "/images/services/french-drains/french-drain-gallery.webp"
    ]
  },
  "landscape-design": {
    "card": "/images/services/landscape-design/favorite-1-card.webp",
    "gallery": [
      "/images/services/landscape-design/favorite-1-gallery.webp",
      "/images/services/landscape-design/favorite-1-gallery.webp",
      "/images/services/landscape-design/favorite-2-gallery.webp",
      "/images/services/landscape-design/favorite-gallery.webp",
      "/images/services/landscape-design/favorite-gallery.webp",
      "/images/services/landscape-design/img-0041-gallery.webp",
      "/images/services/landscape-design/img-0268-gallery.webp",
      "/images/services/landscape-design/img-0269-gallery.webp",
      "/images/services/landscape-design/img-0277-gallery.webp",
      "/images/services/landscape-design/img-0671-gallery.webp",
      "/images/services/landscape-design/img-0718-gallery.webp",
      "/images/services/landscape-design/img-1013-gallery.webp",
      "/images/services/landscape-design/img-1015-gallery.webp",
      "/images/services/landscape-design/img-1061-gallery.webp",
      "/images/services/landscape-design/img-1063-gallery.webp",
      "/images/services/landscape-design/img-1260-gallery.webp",
      "/images/services/landscape-design/img-1557-gallery.webp"
    ]
  },
  "leveling-grading": {
    "card": "/images/services/leveling-grading/img-0402-card.webp",
    "gallery": [
      "/images/services/leveling-grading/img-0402-gallery.webp",
      "/images/services/leveling-grading/img-0430-gallery.webp",
      "/images/services/leveling-grading/img-2457-gallery.webp",
      "/images/services/leveling-grading/img-9326-gallery.webp"
    ]
  },
  "mulch-installation": {
    "card": "/images/services/mulch-installation/img-0269-card.webp",
    "gallery": [
      "/images/services/mulch-installation/img-0269-gallery.webp",
      "/images/services/mulch-installation/img-0270-gallery.webp",
      "/images/services/mulch-installation/img-5461-gallery.webp",
      "/images/services/mulch-installation/img-5500-gallery.webp",
      "/images/services/mulch-installation/img-5503-gallery.webp"
    ]
  },
  "hardscaping": {
    "card": "/images/services/hardscaping/img-0040-card.webp",
    "gallery": [
      "/images/services/hardscaping/img-0040-gallery.webp",
      "/images/services/hardscaping/img-0041-gallery.webp",
      "/images/services/hardscaping/img-0041-gallery.webp",
      "/images/services/hardscaping/img-1058-gallery.webp",
      "/images/services/hardscaping/img-1158-gallery.webp",
      "/images/services/hardscaping/img-1160-gallery.webp",
      "/images/services/hardscaping/img-1164-gallery.webp",
      "/images/services/hardscaping/img-1261-gallery.webp",
      "/images/services/hardscaping/img-1462-gallery.webp",
      "/images/services/hardscaping/img-1800-gallery.webp",
      "/images/services/hardscaping/img-1804-gallery.webp",
      "/images/services/hardscaping/img-1805-gallery.webp",
      "/images/services/hardscaping/img-1881-gallery.webp",
      "/images/services/hardscaping/img-1882-gallery.webp",
      "/images/services/hardscaping/img-1885-gallery.webp",
      "/images/services/hardscaping/img-9143-gallery.webp",
      "/images/services/hardscaping/img-9148-gallery.webp"
    ]
  },
  "residential-concrete": {
    "card": "/images/services/residential-concrete/img-0918-card.webp",
    "gallery": [
      "/images/services/residential-concrete/img-0918-gallery.webp"
    ]
  },
  "retaining-walls": {
    "card": "/images/services/retaining-walls/favorite-card.webp",
    "gallery": [
      "/images/services/retaining-walls/favorite-gallery.webp",
      "/images/services/retaining-walls/img-1033-gallery.webp",
      "/images/services/retaining-walls/img-1081-gallery.webp",
      "/images/services/retaining-walls/img-1085-gallery.webp",
      "/images/services/retaining-walls/img-1429-gallery.webp",
      "/images/services/retaining-walls/img-1430-gallery.webp",
      "/images/services/retaining-walls/img-1524-gallery.webp",
      "/images/services/retaining-walls/img-1525-gallery.webp",
      "/images/services/retaining-walls/img-1526-gallery.webp",
      "/images/services/retaining-walls/img-1527-gallery.webp",
      "/images/services/retaining-walls/img-1768-gallery.webp",
      "/images/services/retaining-walls/img-1769-gallery.webp"
    ]
  },
  "rock-beds": {
    "card": "/images/services/rock-beds/favorite-card.webp",
    "gallery": [
      "/images/services/rock-beds/favorite-gallery.webp",
      "/images/services/rock-beds/img-0655-gallery.webp",
      "/images/services/rock-beds/img-0718-gallery.webp",
      "/images/services/rock-beds/img-0723-gallery.webp",
      "/images/services/rock-beds/img-1059-gallery.webp",
      "/images/services/rock-beds/img-1064-gallery.webp",
      "/images/services/rock-beds/img-1175-gallery.webp",
      "/images/services/rock-beds/img-1463-gallery.webp",
      "/images/services/rock-beds/img-1522-gallery.webp",
      "/images/services/rock-beds/img-1524-gallery.webp",
      "/images/services/rock-beds/img-1759-gallery.webp",
      "/images/services/rock-beds/img-1768-gallery.webp",
      "/images/services/rock-beds/img-1769-gallery.webp"
    ]
  },
  "sod-installation": {
    "card": "/images/services/sod-installation/after-1-card.webp",
    "gallery": [
      "/images/services/sod-installation/after-1-gallery.webp",
      "/images/services/sod-installation/before-1-gallery.webp",
      "/images/services/sod-installation/before-2-gallery.webp",
      "/images/services/sod-installation/img-0991-gallery.webp",
      "/images/services/sod-installation/img-0994-gallery.webp",
      "/images/services/sod-installation/img-1012-gallery.webp",
      "/images/services/sod-installation/img-2066-gallery.webp",
      "/images/services/sod-installation/after-2-gallery.webp"
    ]
  },
  "stone-borders": {
    "card": "/images/services/stone-borders/favorite-card.webp",
    "gallery": [
      "/images/services/stone-borders/favorite-gallery.webp",
      "/images/services/stone-borders/img-1034-gallery.webp",
      "/images/services/stone-borders/img-1038-gallery.webp",
      "/images/services/stone-borders/img-1040-gallery.webp",
      "/images/services/stone-borders/img-1477-gallery.webp",
      "/images/services/stone-borders/img-1478-gallery.webp",
      "/images/services/stone-borders/img-1556-gallery.webp",
      "/images/services/stone-borders/img-1558-gallery.webp",
      "/images/services/stone-borders/img-1603-gallery.webp",
      "/images/services/stone-borders/img-1743-gallery.webp",
      "/images/services/stone-borders/img-1744-gallery.webp",
      "/images/services/stone-borders/img-1746-gallery.webp",
      "/images/services/stone-borders/img-1768-gallery.webp",
      "/images/services/stone-borders/img-1769-gallery.webp"
    ]
  },
  "tree-services": {
    "card": "/images/services/tree-services/b5fb8346-0588-4965-b8ce-309ae61d22ae-card.webp",
    "gallery": [
      "/images/services/tree-services/b5fb8346-0588-4965-b8ce-309ae61d22ae-gallery.webp",
      "/images/services/tree-services/img-0608-gallery.webp",
      "/images/services/tree-services/img-0609-gallery.webp",
      "/images/services/tree-services/img-0610-gallery.webp",
      "/images/services/tree-services/img-1165-gallery.webp",
      "/images/services/tree-services/img-1166-gallery.webp",
      "/images/services/tree-services/img-6435-gallery.webp"
    ]
  },
  "plant-installation": {
    "card": "/images/services/flower-beds/favorite-card.webp",
    "gallery": [
      "/images/services/flower-beds/favorite-gallery.webp",
      "/images/services/flower-beds/img-0267-gallery.webp",
      "/images/services/flower-beds/img-0268-gallery.webp",
      "/images/services/flower-beds/img-0269-gallery.webp",
      "/images/services/flower-beds/img-0270-gallery.webp",
      "/images/services/flower-beds/img-1551-gallery.webp",
      "/images/services/flower-beds/img-1553-gallery.webp",
      "/images/services/flower-beds/img-1557-gallery.webp",
      "/images/services/flower-beds/img-1558-gallery.webp",
      "/images/services/flower-beds/img-1685-gallery.webp",
      "/images/services/flower-beds/img-1687-gallery.webp",
      "/images/services/flower-beds/img-1688-gallery.webp",
      "/images/services/flower-beds/img-1743-gallery.webp",
      "/images/services/flower-beds/img-5478-gallery.webp",
      "/images/services/flower-beds/img-5479-gallery.webp",
      "/images/services/flower-beds/img-5503-gallery.webp",
      "/images/services/landscape-design/favorite-1-gallery.webp",
      "/images/services/landscape-design/favorite-1-gallery.webp",
      "/images/services/landscape-design/favorite-2-gallery.webp",
      "/images/services/landscape-design/favorite-gallery.webp",
      "/images/services/landscape-design/favorite-gallery.webp",
      "/images/services/landscape-design/img-0041-gallery.webp",
      "/images/services/landscape-design/img-0268-gallery.webp",
      "/images/services/landscape-design/img-0269-gallery.webp",
      "/images/services/landscape-design/img-0277-gallery.webp",
      "/images/services/landscape-design/img-0671-gallery.webp",
      "/images/services/landscape-design/img-0718-gallery.webp",
      "/images/services/landscape-design/img-1013-gallery.webp",
      "/images/services/landscape-design/img-1015-gallery.webp",
      "/images/services/landscape-design/img-1061-gallery.webp",
      "/images/services/landscape-design/img-1063-gallery.webp",
      "/images/services/landscape-design/img-1260-gallery.webp",
      "/images/services/landscape-design/img-1557-gallery.webp",
      "/images/services/rock-beds/favorite-gallery.webp",
      "/images/services/rock-beds/img-0655-gallery.webp",
      "/images/services/rock-beds/img-0718-gallery.webp",
      "/images/services/rock-beds/img-0723-gallery.webp",
      "/images/services/rock-beds/img-1059-gallery.webp",
      "/images/services/rock-beds/img-1064-gallery.webp",
      "/images/services/rock-beds/img-1175-gallery.webp",
      "/images/services/rock-beds/img-1463-gallery.webp",
      "/images/services/rock-beds/img-1522-gallery.webp",
      "/images/services/rock-beds/img-1524-gallery.webp",
      "/images/services/rock-beds/img-1759-gallery.webp",
      "/images/services/rock-beds/img-1768-gallery.webp",
      "/images/services/rock-beds/img-1769-gallery.webp"
    ]
  }
};
